# Generated by Django 4.0.3 on 2022-03-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='interviewee',
            fields=[
                ('interviewee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=40)),
                ('resume', models.URLField()),
            ],
        ),
    ]
