# Generated by Django 4.0.3 on 2022-03-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interschedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='date',
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewees',
            field=models.ManyToManyField(to='interschedule.interviewee'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='interview',
            name='st_time',
            field=models.DateTimeField(),
        ),
    ]
