# Generated by Django 4.0.3 on 2022-03-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interschedule', '0002_remove_interview_date_interview_interviewees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewee',
            name='f_name',
            field=models.CharField(max_length=30, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='interviewee',
            name='l_name',
            field=models.CharField(max_length=30, null=True, verbose_name='LastName'),
        ),
    ]
