# Generated by Django 4.0.3 on 2022-03-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interschedule', '0004_alter_interviewee_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewee',
            name='l_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='interviewee',
            name='resume',
            field=models.URLField(blank=True, null=True),
        ),
    ]
