# Generated by Django 4.0.3 on 2022-03-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interschedule', '0005_alter_interviewee_l_name_alter_interviewee_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ('st_time',)},
        ),
    ]
